server:
  port: 8080

spring:
  datasource:
    url: jdbc:hsqldb:mem:hsql://localhost/utility-bill-db
    username: ${HSQL_USERNAME:root}
    password: ${HSQL_PASSWORD:root}
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
    database: HSQL
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml